# Site settings
title: 高天驰 # site title
description: >-
  生活设下枷锁，文字构筑愿景。
lang: zh-CN # default lang
timezone: Asia/Shanghai # set your timezone
image: assets/img/ogp.webp # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/gaotianchi/gaotianchi.github.io # site repo [optional]
mode: light # default theme "dark" | "light"

# <br data-start="94" data-end="97" />
# <br data-start="149" data-end="152" />
# Profile settings
author:
  name: 高天驰 # author name
  bio: >- # 独白
    生活设下枷锁，文字构筑愿景。
  location: 中国 # author location
  username: gaotianchi # general username
  github: gaotianchi # github username
  twitter: gaotianchix # twitter username
  facebook: # facebook username
  email: gaootianchi@qq.com # author email
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://www.gaotianchi.com" #
baseurl:
permalink: /:title/
google_analytics: G-KSMTNEVWS5 # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true
  pages:
    output: true
    permalink: /:path/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false
  - scope:
      path: "_pages"
    values:
      layout: page

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - 模板

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-redirect-from

feed:
  posts_limit: 20
  tags: false
  icon: "/assets/favicon.ico"
  logo: "/assets/favicon.ico"
  excerpt_only: false